In [3]:
import pandas as pd

from google.colab import drive
import pandas as pd
drive.mount('/content/drive')
df=pd.read_csv("/content/drive/My Drive/Colab Notebooks/CarPrice_dataset.csv")
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [4]:
df.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

# Data cleaning

In [6]:
from pandas.core.arrays import categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer

x=df.drop(columns='price')
y=df['price']

categorical_cols=x.select_dtypes(include=['object']).columns.tolist()
numerical_cols=x.select_dtypes(include=['int64','float64']).columns.tolist()


preprocessor=ColumnTransformer(
    transformers=[
        ('num',StandardScaler(),numerical_cols),
        ('car',OneHotEncoder(handle_unknown='ignore'),categorical_cols)
    ]
)


x_processed=preprocessor.fit_transform(x)

x_train,x_test,y_train,y_test=train_test_split(x_processed,y,test_size=0.2,random_state=42)

# Model Building

In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    
    Dense(512, activation='relu', input_shape=(x_train.shape[1],)),  # Hidden Layer 1
    Dense(256, activation='relu'),
    Dense(128, activation='relu'),  
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)                                                         # Output Layer
])
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 512)            │       102,912 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 277,505 (1.06 MB)

 Trainable params: 277,505 (1.06 MB)

 Non-trainable params: 0 (0.00 B)

# Train the model

In [9]:
model.compile(
    optimizer='adam',
    loss='mean_absolute_error',
    metrics=['mean_absolute_error','mean_squared_error']
)

In [10]:
history = model.fit(
    x_train,
    y_train,
    epochs=90,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 6s 624ms/step - loss: 12367.0664 - mean_absolute_error: 12367.0664 - mean_squared_error: 201130256.0000 - val_loss: 15080.2803 - val_mean_absolute_error: 15080.2803 - val_mean_squared_error: 317853344.0000
Epoch 2/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 13198.5449 - mean_absolute_error: 13198.5449 - mean_squared_error: 231252144.0000 - val_loss: 15071.7227 - val_mean_absolute_error: 15071.7227 - val_mean_squared_error: 317575072.0000
Epoch 3/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 12491.3301 - mean_absolute_error: 12491.3301 - mean_squared_error: 206897600.0000 - val_loss: 15047.6143 - val_mean_absolute_error: 15047.6143 - val_mean_squared_error: 316806688.0000
Epoch 4/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 12700.9844 - mean_absolute_error: 12700.9844 - mean_squared_error: 211839984.0000 - val_loss: 14983.9414 - val_mean_absolute_error: 14983.9414 - val_mean_squared_error: 314802560.0000
Epoch 5/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 12251.1680 - mean_absolute_error: 12251.1680 - mean_squared_error: 200485088.0000 - val_loss: 14832.1885 - val_mean_absolute_error: 14832.1885 - val_mean_squared_error: 310142944.0000
Epoch 6/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 12479.4814 - mean_absolute_error: 12479.4814 - mean_squared_error: 204857936.0000 - val_loss: 14497.0918 - val_mean_absolute_error: 14497.0918 - val_mean_squared_error: 300259808.0000
Epoch 7/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 11906.8428 - mean_absolute_error: 11906.8428 - mean_squared_error: 193062832.0000 - val_loss: 13801.3340 - val_mean_absolute_error: 13801.3340 - val_mean_squared_error: 280884032.0000
Epoch 8/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 11293.8477 - mean_absolute_error: 11293.8477 - mean_squared_error: 177933312.0000 - val_loss: 12430.8232 - val_mean_absolute_error: 12430.8232 - val_mean_squared_error: 246256096.0000
Epoch 9/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 9434.4131 - mean_absolute_error: 9434.4131 - mean_squared_error: 142427472.0000 - val_loss: 9943.1680 - val_mean_absolute_error: 9943.1680 - val_mean_squared_error: 191599136.0000
Epoch 10/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - loss: 7036.9629 - mean_absolute_error: 7036.9629 - mean_squared_error: 102092320.0000 - val_loss: 7626.6743 - val_mean_absolute_error: 7626.6743 - val_mean_squared_error: 122836080.0000
Epoch 11/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 5870.7578 - mean_absolute_error: 5870.7578 - mean_squared_error: 66253748.0000 - val_loss: 6221.9287 - val_mean_absolute_error: 6221.9287 - val_mean_squared_error: 75165592.0000
Epoch 12/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 4796.1885 - mean_absolute_error: 4796.1885 - mean_squared_error: 36236328.0000 - val_loss: 4691.4243 - val_mean_absolute_error: 4691.4243 - val_mean_squared_error: 51909368.0000
Epoch 13/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 3676.2153 - mean_absolute_error: 3676.2153 - mean_squared_error: 32131584.0000 - val_loss: 3591.8254 - val_mean_absolute_error: 3591.8254 - val_mean_squared_error: 37973456.0000
Epoch 14/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2277.5891 - mean_absolute_error: 2277.5891 - mean_squared_error: 16047684.0000 - val_loss: 3254.9163 - val_mean_absolute_error: 3254.9163 - val_mean_squared_error: 27753636.0000
Epoch 15/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 2212.6006 - mean_absolute_error: 2212.6006 - mean_squared_error: 16671302.0000 - val_loss: 2602.5479 - val_mean_absolute_error: 2602.5479 - val_mean_squared_error: 14956778.0000
Epoch 16/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2444.6968 - mean_absolute_error: 2444.6968 - mean_squared_error: 14975899.0000 - val_loss: 2518.4404 - val_mean_absolute_error: 2518.4404 - val_mean_squared_error: 12462953.0000
Epoch 17/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 2032.1470 - mean_absolute_error: 2032.1470 - mean_squared_error: 10302090.0000 - val_loss: 3194.1643 - val_mean_absolute_error: 3194.1643 - val_mean_squared_error: 19952036.0000
Epoch 18/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 2344.8184 - mean_absolute_error: 2344.8184 - mean_squared_error: 12089897.0000 - val_loss: 3084.9829 - val_mean_absolute_error: 3084.9829 - val_mean_squared_error: 21046340.0000
Epoch 19/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 2161.3315 - mean_absolute_error: 2161.3315 - mean_squared_error: 13843058.0000 - val_loss: 2577.6169 - val_mean_absolute_error: 2577.6169 - val_mean_squared_error: 15256869.0000
Epoch 20/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 1988.3724 - mean_absolute_error: 1988.3724 - mean_squared_error: 10525661.0000 - val_loss: 2964.2688 - val_mean_absolute_error: 2964.2688 - val_mean_squared_error: 22455188.0000
Epoch 21/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 1825.7627 - mean_absolute_error: 1825.7627 - mean_squared_error: 10361631.0000 - val_loss: 3512.6431 - val_mean_absolute_error: 3512.6431 - val_mean_squared_error: 30992786.0000
Epoch 22/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 1736.8953 - mean_absolute_error: 1736.8953 - mean_squared_error: 10093457.0000 - val_loss: 2782.9199 - val_mean_absolute_error: 2782.9199 - val_mean_squared_error: 19635532.0000
Epoch 23/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 1880.5367 - mean_absolute_error: 1880.5367 - mean_squared_error: 10504280.0000 - val_loss: 2507.3853 - val_mean_absolute_error: 2507.3853 - val_mean_squared_error: 14384758.0000
Epoch 24/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 1666.6061 - mean_absolute_error: 1666.6061 - mean_squared_error: 6683025.0000 - val_loss: 2935.8630 - val_mean_absolute_error: 2935.8630 - val_mean_squared_error: 20205396.0000
Epoch 25/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 1691.9470 - mean_absolute_error: 1691.9470 - mean_squared_error: 9315119.0000 - val_loss: 2727.4207 - val_mean_absolute_error: 2727.4207 - val_mean_squared_error: 17354826.0000
Epoch 26/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 1330.7787 - mean_absolute_error: 1330.7787 - mean_squared_error: 5136448.5000 - val_loss: 2379.8391 - val_mean_absolute_error: 2379.8391 - val_mean_squared_error: 12767420.0000
Epoch 27/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 1468.5876 - mean_absolute_error: 1468.5876 - mean_squared_error: 5169746.5000 - val_loss: 2420.8489 - val_mean_absolute_error: 2420.8489 - val_mean_squared_error: 13573898.0000
Epoch 28/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 1352.5664 - mean_absolute_error: 1352.5664 - mean_squared_error: 5621204.0000 - val_loss: 2562.1602 - val_mean_absolute_error: 2562.1602 - val_mean_squared_error: 15277207.0000
Epoch 29/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 1244.4127 - mean_absolute_error: 1244.4127 - mean_squared_error: 4580132.0000 - val_loss: 2373.8896 - val_mean_absolute_error: 2373.8896 - val_mean_squared_error: 12483624.0000
Epoch 30/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 1211.6223 - mean_absolute_error: 1211.6223 - mean_squared_error: 4396837.5000 - val_loss: 2572.8518 - val_mean_absolute_error: 2572.8518 - val_mean_squared_error: 15130938.0000
Epoch 31/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 1246.8267 - mean_absolute_error: 1246.8267 - mean_squared_error: 5798165.0000 - val_loss: 2477.6006 - val_mean_absolute_error: 2477.6006 - val_mean_squared_error: 14040628.0000
Epoch 32/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 1205.1176 - mean_absolute_error: 1205.1176 - mean_squared_error: 4604362.0000 - val_loss: 2486.3120 - val_mean_absolute_error: 2486.3120 - val_mean_squared_error: 14063352.0000
Epoch 33/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 1167.5232 - mean_absolute_error: 1167.5232 - mean_squared_error: 4033054.0000 - val_loss: 2373.2344 - val_mean_absolute_error: 2373.2344 - val_mean_squared_error: 11977974.0000
Epoch 34/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 1191.8250 - mean_absolute_error: 1191.8250 - mean_squared_error: 4269919.0000 - val_loss: 2469.0886 - val_mean_absolute_error: 2469.0886 - val_mean_squared_error: 13343800.0000
Epoch 35/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 1033.7632 - mean_absolute_error: 1033.7632 - mean_squared_error: 3304415.0000 - val_loss: 2372.0098 - val_mean_absolute_error: 2372.0098 - val_mean_squared_error: 12071961.0000
Epoch 36/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1025.6324 - mean_absolute_error: 1025.6324 - mean_squared_error: 2819348.0000 - val_loss: 2326.6189 - val_mean_absolute_error: 2326.6189 - val_mean_squared_error: 11584854.0000
Epoch 37/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 1030.1914 - mean_absolute_error: 1030.1914 - mean_squared_error: 3686677.7500 - val_loss: 2424.7839 - val_mean_absolute_error: 2424.7839 - val_mean_squared_error: 12635334.0000
Epoch 38/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 1034.4493 - mean_absolute_error: 1034.4493 - mean_squared_error: 3076259.0000 - val_loss: 2400.5107 - val_mean_absolute_error: 2400.5107 - val_mean_squared_error: 12864173.0000
Epoch 39/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 943.1982 - mean_absolute_error: 943.1982 - mean_squared_error: 3144867.5000 - val_loss: 2312.1274 - val_mean_absolute_error: 2312.1274 - val_mean_squared_error: 11923417.0000
Epoch 40/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1002.7343 - mean_absolute_error: 1002.7343 - mean_squared_error: 3380762.0000 - val_loss: 2547.4512 - val_mean_absolute_error: 2547.4512 - val_mean_squared_error: 14191280.0000
Epoch 41/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 1031.6514 - mean_absolute_error: 1031.6514 - mean_squared_error: 3207899.0000 - val_loss: 2218.8801 - val_mean_absolute_error: 2218.8801 - val_mean_squared_error: 10854113.0000
Epoch 42/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 1055.7532 - mean_absolute_error: 1055.7532 - mean_squared_error: 2740665.0000 - val_loss: 2123.9023 - val_mean_absolute_error: 2123.9023 - val_mean_squared_error: 9903451.0000
Epoch 43/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 959.7045 - mean_absolute_error: 959.7045 - mean_squared_error: 2127958.5000 - val_loss: 2332.5879 - val_mean_absolute_error: 2332.5879 - val_mean_squared_error: 11386990.0000
Epoch 44/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 901.0657 - mean_absolute_error: 901.0657 - mean_squared_error: 2122635.5000 - val_loss: 2292.3201 - val_mean_absolute_error: 2292.3201 - val_mean_squared_error: 11550107.0000
Epoch 45/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 912.7867 - mean_absolute_error: 912.7867 - mean_squared_error: 2425283.2500 - val_loss: 2613.6992 - val_mean_absolute_error: 2613.6992 - val_mean_squared_error: 15900174.0000
Epoch 46/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 968.2114 - mean_absolute_error: 968.2114 - mean_squared_error: 2376929.0000 - val_loss: 2307.8079 - val_mean_absolute_error: 2307.8079 - val_mean_squared_error: 12138544.0000
Epoch 47/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 743.5654 - mean_absolute_error: 743.5654 - mean_squared_error: 1445547.5000 - val_loss: 2296.1169 - val_mean_absolute_error: 2296.1169 - val_mean_squared_error: 11761245.0000
Epoch 48/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 730.6276 - mean_absolute_error: 730.6276 - mean_squared_error: 1407697.3750 - val_loss: 2145.9067 - val_mean_absolute_error: 2145.9067 - val_mean_squared_error: 10050320.0000
Epoch 49/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 788.0303 - mean_absolute_error: 788.0303 - mean_squared_error: 1541133.1250 - val_loss: 2246.9375 - val_mean_absolute_error: 2246.9375 - val_mean_squared_error: 11269119.0000
Epoch 50/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 698.0321 - mean_absolute_error: 698.0321 - mean_squared_error: 1400316.5000 - val_loss: 2336.6963 - val_mean_absolute_error: 2336.6963 - val_mean_squared_error: 12116521.0000
Epoch 51/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 734.6351 - mean_absolute_error: 734.6351 - mean_squared_error: 1532584.8750 - val_loss: 2264.5190 - val_mean_absolute_error: 2264.5190 - val_mean_squared_error: 11421095.0000
Epoch 52/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 717.5229 - mean_absolute_error: 717.5229 - mean_squared_error: 1389410.6250 - val_loss: 2126.5693 - val_mean_absolute_error: 2126.5693 - val_mean_squared_error: 9683024.0000
Epoch 53/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 678.5928 - mean_absolute_error: 678.5928 - mean_squared_error: 1235929.7500 - val_loss: 2211.5901 - val_mean_absolute_error: 2211.5901 - val_mean_squared_error: 10736628.0000
Epoch 54/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 675.2152 - mean_absolute_error: 675.2152 - mean_squared_error: 1324661.0000 - val_loss: 2234.2402 - val_mean_absolute_error: 2234.2402 - val_mean_squared_error: 11170526.0000
Epoch 55/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 620.9375 - mean_absolute_error: 620.9375 - mean_squared_error: 1076798.5000 - val_loss: 2301.8440 - val_mean_absolute_error: 2301.8440 - val_mean_squared_error: 12038996.0000
Epoch 56/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 701.0009 - mean_absolute_error: 701.0009 - mean_squared_error: 1414779.3750 - val_loss: 2142.3796 - val_mean_absolute_error: 2142.3796 - val_mean_squared_error: 10304372.0000
Epoch 57/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 604.4078 - mean_absolute_error: 604.4078 - mean_squared_error: 932831.1250 - val_loss: 2158.0444 - val_mean_absolute_error: 2158.0444 - val_mean_squared_error: 10406685.0000
Epoch 58/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 653.7042 - mean_absolute_error: 653.7042 - mean_squared_error: 1093496.8750 - val_loss: 2101.2480 - val_mean_absolute_error: 2101.2480 - val_mean_squared_error: 9610002.0000
Epoch 59/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 627.8303 - mean_absolute_error: 627.8303 - mean_squared_error: 1073465.0000 - val_loss: 2124.7632 - val_mean_absolute_error: 2124.7632 - val_mean_squared_error: 10446881.0000
Epoch 60/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 642.8389 - mean_absolute_error: 642.8389 - mean_squared_error: 1164651.8750 - val_loss: 2109.7312 - val_mean_absolute_error: 2109.7312 - val_mean_squared_error: 10528944.0000
Epoch 61/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 563.9025 - mean_absolute_error: 563.9025 - mean_squared_error: 756375.6250 - val_loss: 2131.7844 - val_mean_absolute_error: 2131.7844 - val_mean_squared_error: 10616343.0000
Epoch 62/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 557.1415 - mean_absolute_error: 557.1415 - mean_squared_error: 973364.2500 - val_loss: 2141.7734 - val_mean_absolute_error: 2141.7734 - val_mean_squared_error: 10838924.0000
Epoch 63/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 495.9793 - mean_absolute_error: 495.9793 - mean_squared_error: 784356.8125 - val_loss: 2134.7192 - val_mean_absolute_error: 2134.7192 - val_mean_squared_error: 10290811.0000
Epoch 64/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 513.6381 - mean_absolute_error: 513.6381 - mean_squared_error: 864514.7500 - val_loss: 2125.3960 - val_mean_absolute_error: 2125.3960 - val_mean_squared_error: 9780880.0000
Epoch 65/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 436.8764 - mean_absolute_error: 436.8764 - mean_squared_error: 617114.0625 - val_loss: 2143.2729 - val_mean_absolute_error: 2143.2729 - val_mean_squared_error: 10201485.0000
Epoch 66/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 415.0965 - mean_absolute_error: 415.0965 - mean_squared_error: 602721.1250 - val_loss: 2158.8362 - val_mean_absolute_error: 2158.8362 - val_mean_squared_error: 10492592.0000
Epoch 67/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 489.6599 - mean_absolute_error: 489.6599 - mean_squared_error: 696992.0000 - val_loss: 2109.7036 - val_mean_absolute_error: 2109.7036 - val_mean_squared_error: 9372027.0000
Epoch 68/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 447.4672 - mean_absolute_error: 447.4672 - mean_squared_error: 602001.5625 - val_loss: 2214.6338 - val_mean_absolute_error: 2214.6338 - val_mean_squared_error: 10906541.0000
Epoch 69/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 451.7913 - mean_absolute_error: 451.7913 - mean_squared_error: 617191.9375 - val_loss: 2133.3052 - val_mean_absolute_error: 2133.3052 - val_mean_squared_error: 9377472.0000
Epoch 70/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 523.8396 - mean_absolute_error: 523.8396 - mean_squared_error: 650828.7500 - val_loss: 2189.7642 - val_mean_absolute_error: 2189.7642 - val_mean_squared_error: 10288549.0000
Epoch 71/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 494.8695 - mean_absolute_error: 494.8695 - mean_squared_error: 626778.6875 - val_loss: 2084.8784 - val_mean_absolute_error: 2084.8784 - val_mean_squared_error: 8751086.0000
Epoch 72/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 639.3016 - mean_absolute_error: 639.3016 - mean_squared_error: 839501.1250 - val_loss: 2158.1060 - val_mean_absolute_error: 2158.1060 - val_mean_squared_error: 10070474.0000
Epoch 73/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 424.9805 - mean_absolute_error: 424.9805 - mean_squared_error: 535746.0625 - val_loss: 2069.9561 - val_mean_absolute_error: 2069.9561 - val_mean_squared_error: 8553431.0000
Epoch 74/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 420.6328 - mean_absolute_error: 420.6328 - mean_squared_error: 523132.5938 - val_loss: 2181.0342 - val_mean_absolute_error: 2181.0342 - val_mean_squared_error: 9916968.0000
Epoch 75/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 475.2614 - mean_absolute_error: 475.2614 - mean_squared_error: 578075.6250 - val_loss: 2154.7424 - val_mean_absolute_error: 2154.7424 - val_mean_squared_error: 9584514.0000
Epoch 76/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 411.5027 - mean_absolute_error: 411.5027 - mean_squared_error: 527065.5625 - val_loss: 2113.1462 - val_mean_absolute_error: 2113.1462 - val_mean_squared_error: 8947467.0000
Epoch 77/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 395.7881 - mean_absolute_error: 395.7881 - mean_squared_error: 467358.4375 - val_loss: 2140.9441 - val_mean_absolute_error: 2140.9441 - val_mean_squared_error: 9593578.0000
Epoch 78/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 365.0709 - mean_absolute_error: 365.0709 - mean_squared_error: 489524.2812 - val_loss: 2157.1467 - val_mean_absolute_error: 2157.1467 - val_mean_squared_error: 9783755.0000
Epoch 79/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 344.8422 - mean_absolute_error: 344.8422 - mean_squared_error: 339461.7188 - val_loss: 2094.0537 - val_mean_absolute_error: 2094.0537 - val_mean_squared_error: 8583176.0000
Epoch 80/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 411.8166 - mean_absolute_error: 411.8166 - mean_squared_error: 473999.1875 - val_loss: 2114.5127 - val_mean_absolute_error: 2114.5127 - val_mean_squared_error: 8922687.0000
Epoch 81/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 351.8167 - mean_absolute_error: 351.8167 - mean_squared_error: 368082.1562 - val_loss: 2097.0400 - val_mean_absolute_error: 2097.0400 - val_mean_squared_error: 8903948.0000
Epoch 82/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 334.8681 - mean_absolute_error: 334.8681 - mean_squared_error: 329104.6875 - val_loss: 2056.6614 - val_mean_absolute_error: 2056.6614 - val_mean_squared_error: 8229608.5000
Epoch 83/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 367.1734 - mean_absolute_error: 367.1734 - mean_squared_error: 367225.7500 - val_loss: 2157.9521 - val_mean_absolute_error: 2157.9521 - val_mean_squared_error: 9368799.0000
Epoch 84/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 353.0280 - mean_absolute_error: 353.0280 - mean_squared_error: 393771.6250 - val_loss: 2139.6733 - val_mean_absolute_error: 2139.6733 - val_mean_squared_error: 8673454.0000
Epoch 85/90
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 379.2204 - mean_absolute_error: 379.2204 - mean_squared_error: 367350.1562 - val_loss: 2302.7026 - val_mean_absolute_error: 2302.7026 - val_mean_squared_error: 10781382.0000
Epoch 86/90

In [12]:
#model Evaluation
from sklearn.metrics import *
y_pred = model.predict(x_test)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("R² Score:", r2)

2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 547ms/step
Mean Absolute Error: 1908.2303613757622
Mean Squared Error: 8823206.433961865
R² Score: 0.8882346460739317

In [18]:
new_data=x.iloc[[0]]
new_data_precessed=preprocessor.transform(new_data)
predicted_price = model.predict(new_data_precessed)
print("Predicted Car Price: ₹", int(predicted_price[0][0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 416ms/step
Predicted Car Price: ₹ 13620